name: flutter_carplay
description: Build native Apple CarPlay and Android Auto interfaces from Flutter using platform templates, callbacks and shared app logic.
version: 1.7.0+1
homepage: https://github.com/oguzhnatly/flutter_carplay#readme
repository: https://github.com/oguzhnatly/flutter_carplay
issue_tracker: https://github.com/oguzhnatly/flutter_carplay/issues

environment:
  sdk: ">=3.12.0 <4.0.0"
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  uuid: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: SwiftFlutterCarplayPlugin
      android:
        package: com.oguzhnatly.flutter_android_auto
        pluginClass: FlutterAndroidAutoPlugin
