enum FCPChannelTypes {
  onCarplayConnectionChange,
  setRootTemplate,
  forceUpdateRootTemplate,
  updateListItem,
  updateListImageRowItem,
  onFCPListItemSelected,
  onFCPListItemSelectedComplete,
  onFCPListImageRowItemSelected,
  onFCPListImageRowItemSelectedComplete,
  onFCPListImageRowItemElementSelected,
  onFCPListImageRowItemElementSelectedComplete,
  onFCPAlertActionPressed,
  setAlert,
  onPresentStateChanged,
  popTemplate,
  closePresent,
  pushTemplate,
  showNowPlaying,
  onGridButtonPressed,
  setActionSheet,
  onBarButtonPressed,
  onTextButtonPressed,
  popToRootTemplate,
  onScreenBackButtonPressed,
}

enum FAAChannelTypes {
  onAndroidAutoConnectionChange,
  setRootTemplate,
  forceUpdateRootTemplate,
  pushTemplate,
  popTemplate,
  popToRootTemplate,
  onListItemSelected,
  onListItemSelectedComplete,
  onScreenBackButtonPressed,
}
